name: Hello, World!
on: push

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - run: docker-compose up --build -d
            - run: rails db:create
            - run: rails db:migrate
            - run: rails test
