name: Hello, World!
on: push

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - run: docker-compose up --build -d
            - run: docker-compose exec -T --env 'RAILS_ENV=test' web rails db:create
            - run: docker-compose exec -T --env 'RAILS_ENV=test' web rails db:migrate
            - run: docker-compose exec -T --env 'RAILS_ENV=test' web rails test
